# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpoonacularAmaris' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpoonacularAmaris
  pod 'Alamofire'

  target 'SpoonacularAmarisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpoonacularAmarisUITests' do
    # Pods for testing
  end

end
